name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: "16.6.0"

jobs:
  build:
    name: Build program and test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm i
      - name: Compile
        run: tsc
